import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className="
            flex
          "
        >
          <div 
            className="
              xl:w-[15%]
              lg:w-[20%]
              md:w-[25%]
            "
          >
            <Sidebar />
          </div>
          <div
            className="flex-1 relative"
          >
            <div
              className="sticky"
            >
              <Navbar />
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
