import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className="
            flex
            relative
          "
        >
          <div 
            className="
              xl:w-[15%]
              lg:w-[20%]
              sm:w-[25%]
              w-[15%]
              h-full
              fixed
              top-0
              left-0
            "
          >
            <Sidebar />
          </div>
          <div
            className="flex-1 relative xl:ml-[15%] lg:ml-[20%] sm:ml-[25%] ml-[15%]"
          >
            <div
              className="sticky top-0"
            >
              <Navbar />
            </div>
            <div className="h-full overflow-scroll">
            {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
